### ISSUE TITLE
this methods of jailbreak detection does not work if...

### ISSUE THREAD

**Issue by hamiltonalex** [Shmoopi/AntiPiracy#1]
Hello,

I have found that if application "xCon" ver 38 is installed on the jailbroken iOS device then all your detection fails... And this is very frustrating...

**Comment by Shmoopi** [comment]
Thanks for letting us know!

We've provided the jailbreak check merely as a guide for other developers to learn from and improve upon, not to rely on as a failsafe solution. At least, that's the hope.

Ideally, developers will change these checks or create new checks that circumvent "xCon".  Please feel free to contribute if you have any new checks that help overcome it's anti-detection algorithms or if you have any insight.
